### ISSUE TITLE
Multiple Button Types

### ISSUE THREAD

**Issue by boatarmor** [kimballa/button-debounce#2]
kimballa,

What would be the correct way to implement multiple buttons with different functions?  I'm working on a project that uses three buttons to operate a single solenoid at 5Hz; the first two are simple "press once & do stuff", but the third requires the button to be held down for as long as the user wants the program to run (see example below).  Any help getting pointed in the right direction would be much appreciated!

TLDR:

- Button 1:  Auto Mode (single press)
- Button 2:  Cancel Auto Mode (single press)
- Button 3:  Manual Mode (press and hold to do stuff)

Long Example:

- Button 1:  Press once to run program in "auto mode".  (bit-bang PWM on Pin 5 for a set duration of 80 seconds).
- Button 2:  Press once to cancel "auto mode".  (set Pin 5 LOW any time before the 80 second duration has elapsed.)
- Button 3:  Press and hold to run the program in "manual" mode.  (bit-bang PWM on Pin 5 for as long as the button is held LOW, 
                   releasing the button to HIGH sets "Pin X" LOW.)

**Comment by kimballa** [comment]
Hi boatarmor, 

You need a `Button` instance for each button; each of these is connected to a different digital pin, and programmed to run a different `btn_handler_t` function. All of these functions are dealing with ongoing activity on pin 5 that would be handled in the `loop()` function, so really your button handler functions are updating some sort of state variable that tells your main loop what to do each cycle.

Expanding on the example in `buttons.ino`, you probably want something like this:

```c++
// Your 3 buttons are connected to some GPIO pins, change these to whatever your pinout is.
static constexpr int AUTO_PIN = 6;
static constexpr int CANCEL_PIN = 7;
static constexpr int MANUAL_PIN = 8;

static constexpr unsigned int MODE_NOT_RUNNING = 0;
static constexpr unsigned int MODE_AUTO = 1;
static constexpr unsigned int MODE_MANUAL = 2;

static unsigned int mode = MODE_NOT_RUNNING; // What mode is our main loop in?
static unsigned long autoStartTime; // when was the last time we started auto mode?
static constexpr unsigned long AUTO_DURATION_MILLIS = 80000; // 80 seconds.

void buttonHandlerAuto(uint8_t btnId, uint8_t btnState) {
  if (btnState == BTN_PRESSED) {
    Serial.println("Switching to automatic");
    autoStartTime = millis(); // we just switched into automatic mode. 
    mode = MODE_AUTO;
/* Note:
 If we were already in auto mode already, this will reset the timer.
 If you don't want repeated presses of the auto button to reset the timer, then don't
 update autoStartTime if we're already in MODE_AUTO.
*/ 
  } else {
    // btnState == BTN_OPEN. Nothing to do.
  }
}

void buttonHandlerCancel(uint8_t btnId, uint8_t btnState) {
  if (btnState == BTN_PRESSED) {
    // Stop doing anything.
    Serial.println("Stopping PWM program, user has canceled");
    mode = MODE_NOT_RUNNING;
  }
}

void buttonHandlerManual(uint8_t btnId, uint8_t btnState) {
  if (btnState == BTN_PRESSED) {
    Serial.println("User has started manual mode.");
    mode = MODE_MANUAL;
  } else {
    // User has released the button. Stop.
    Serial.println("Stopping manual mode.");
    mode = MODE_NOT_RUNNING;
  }
}

// Define your buttons with a unique id and handler function each.
static Button autoButton(0, buttonHandlerAuto);
static Button cancelButton(1, buttonHandlerCancel);
static Button manualButton(2, buttonHandlerManual);

void setup() {
  Serial.begin(115200);
  pinMode(AUTO_PIN, INPUT_PULLUP);
  pinMode(MANUAL_PIN, INPUT_PULLUP);
  pinMode(CANCEL_PIN, INPUT_PULLUP);
}

static void pollButtons() {
  // update() will call the buttonHandler fn for each button if the pin
  // transitions to a new state and stays there
  // for multiple reads over 25+ ms.
  autoButton.update(digitalRead(AUTO_PIN));
  cancelButton.update(digitalRead(CANCEL_PIN));
  manualButton.update(digitalRead(MANUAL_PIN));
}

static void doNextPwmTick() {
  // exercise left for reader to fill this out.
}

void loop() {
  pollButtons(); // Poll your buttons every loop.
  if (mode == MODE_MANUAL) {
    // User is holding down the manual button. Do the bit-bang.
    doNextPwmTick();
  } else if (mode == MODE_AUTO) {
    // We have been placed in auto mode by the buttons either this cycle or a prior cycle.
    unsigned long autoStopTime = autoStartTime + AUTO_DURATION_MILLIS;
    if (millis > autoStopTime) {
      // The automatic mode has gone on long enough. Now we stop.
      Serial.println("Automatic mode timed out.");
      mode = MODE_NOT_RUNNING; // Stop PWM until user restarts it one way or another.
    } else {
      // Auto mode still active.
      doNextPwmTick();
    }
  }

  if (mode == MODE_NOT_RUNNING) {
    // We're no longer / not running PWM, so we hold the pin low.
    digitalWrite(5, LOW);
  }

  delay(10); // Loop iterations should run fairly quickly, 10's of ms, not 100's.
}
```

**Comment by kimballa** [comment]
Note that you need your `loop()` to run pretty quickly (I have it every 10ms here) if you want the buttons to feel responsive. If you only run the loop every 200ms (when it's time to toggle the pwm pin), the buttons will be sluggish. They will not register a press for shorter than 2/5 a second, and the user will need to hold the button for at least 400ms to be registered, because the debouncing means the same signal has to be confirmed with two successive reads at least one debounce interval apart. (The debounce interval is set by default to 25ms, but if you read the gpio pins more slowly than that, then that slower interval takes over.)

The debounce interval can be modified if you think 25ms is too fast and you want the user to need to press for longer than that -- check the API for details. I've found it's a reasonable amount of time though and your hardware should definitely be stable long before that, 25ms is an eternity in electronics.

In any case, your `doNextPwmTick()` function will need to decide if it's been long enough since the last state transition rather than just toggle low/high every time it's called by `loop()`. Use the `millis()` function and save the last time you did a transition in a global variable, and compare to see if it's been long enough, and then switch the state (save the last pwm pin state in a global variable too, like the `blink.ino` stock Arduino example does).

**Comment by boatarmor** [comment]
Thank you a ton!  Big time appreciate you taking the time to offer the explanation and example.    I'll get this wrote in and give it a go.  Thanks again and take care!

**Comment by kimballa** [comment]
Good luck!
Marking this closed.
