### ISSUE TITLE
Long hold

### ISSUE THREAD

**Issue by tomaustin700** [kimballa/button-debounce#3]
Hey man, really like this library and use it in all my projects that have button logic. Have you thought about implementing a long hold? I think it could be a really useful feature to have.

Cheers

**Comment by kimballa** [comment]
Hey glad you find it useful!

The buttons all start with a default timing that I found is electrically reliable for "close to instant only-once press/release", but you can call `btn.setPushDebounceInterval()` to require a long human-perceptible push-hold time before transitioning states and calling your BtnHandler function. Try 1000 ms or more.

You can also tailor `setReleaseDebounceInterval()` to fire the button handler at a time fairly delayed after the user releases the button although that's a bit weirder of ux.

A long Push interval followed by a short Release interval with your code watching for a state transition from "pushed" to "released" can be used to require the user to hold for a second or two (or whatever) to "arm" the action but won't actually trigger the action to fire until they let go of the button. 

Note that since the `Button` instance itself doesn't have a direct tie-in to the actual gpio mechanism (you still need to read gpio yourself and pass the current reading to the update function), you can have two `Button` instances that are associated with the same physical tactile switch. So you can have separate "short press" and "long press" Button function dispatchers for the same physical button with different debounce intervals if you want to.

Does that get you where you need to go? Or is your problem a little different?

**Comment by kimballa** [comment]
I just realized, I actually demonstrated this usage in one of the included examples - see https://github.com/kimballa/button-debounce/blob/main/examples/pressAndHold/pressAndHold.ino

**Comment by tomaustin700** [comment]
Thanks @kimballa, I actually needed my buttons to work normally but allow long hold to execute some different logic so I think it needed something slightly different to your example. I was able to implement something myself like this though:

```cpp
static void switchHandler(uint8_t btnId, uint8_t btnState) {

  if (btnState == BTN_PRESSED && (btnId == 4 || btnId == 5) && millis() > (longHoldStartMillis + 3000)){
      //LONG HOLD
  }

  if (btnState == BTN_PRESSED) {
  //NORMAL LOGIC
  }


  if (btnState == BTN_OPEN) {
    longHoldStartMillis = millis();
  }
}
``` 

Which got the job done. Thanks for the quick reply though :)

**Comment by kimballa** [comment]
Glad you are unblocked!

I am going to reopen this issue to track for writing and adding another example. I think it lets you do (what I think you want) more cleanly.

I think your code as-written is going to fire the "long hold" code after only a short press which follows a prior press/release cycle by 3 or more seconds, rather than actually require the user hold the button down.

**Comment by kimballa** [comment]
@tomaustin700 Have a look at https://github.com/kimballa/button-debounce/blob/main/examples/multiActionBtn/multiActionBtn.ino -- I think this might be more like what you're looking for.

**Comment by marcvillanuevamir** [comment]
Hi @kimballa ! Thank you very much for your development and support! I come back to this thread because I am using your multi action button example, but I'd like it to effectively switch between different actions without triggering other actions. For that, it would make sense for me to trigger the action on button release, but as soon as I release the long push button, the short push button gets triggered as well. I have been trying to flag them to not much avail, so I'd be grateful if you could give me a hint or provide an example where different actions don't interfere with each other. Thank you so much!
